### ISSUE TITLE
Command line not working

### ISSUE THREAD

**Issue by bichotll** [papnkukn/subsrt#3]
Hi, your script looks promising, but it didn't work for me when I tried to install it globally and run it:

```
$ subsrt
module.js:538
    throw err;
    ^

Error: Cannot find module '../subsrt.js'
```

I may take a look myself in case I don't find an alternative.

**Comment by arcman77** [comment]
have you tried checking your node_module subfolder?

**Comment by papnkukn** [comment]
Solved
